### PR TITLE
Fixes and new people and blog pages

### PR DESCRIPTION
**Pull request by pepaaran**
I noticed that when clicking on the icons in the personal pages, they would lead to a non-existent page in the website, or to the ORCID login rather than the actual page. For the emails I used `mailto:` links.

This pull request also includes the profiles of Jaideep and Didem.

### CODE REVIEW

**Comment by khufkens** [comment]
@pepaaran Could you update to blogdown version 110 (in the .Rprofile)? This should fix the error. Alternatively adjust the workflow in `.github` and specify the blogdown version.

**Comment by khufkens** [comment]
Replace `blogdown::install_hugo()` with `blogdown::install_hugo("0.104.3")` here:
https://github.com/computationales/geco_website/blob/592ac3bf13556e3f70a564438ea5141e591f17d2/.github/workflows/deploy-blogdown.yaml#L37

**Comment by pepaaran** [comment]
Now only the netlify check fail (which we agreed to ignore, right?). I just changed the hugo version in the `.github` workflow. This PR is good to go, in my opinion.

**Comment by stineb** [comment]
Thanks @pepaaran and @khufkens !

**Pull request merged**
